# Generated by Django 5.1.4 on 2025-01-19 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publisher_date',
            new_name='publication_date',
        ),
    ]
